// resume actions constants
export const RESUME_LOADING = 'RESUME_LOADING';
export const RESUME_LOADED = 'RESUME_LOADED';
export const RESUME_FAILED = 'RESUME_FAILED';
export const MAIN_RESUME_LOADING = 'MAIN_RESUME_LOADING';
export const MAIN_RESUME_LOADED = 'MAIN_RESUME_LOADED';
export const MAIN_RESUME_FAILED = 'MAIN_RESUME_FAILED';
export const UPDATE_RESUME = 'UPDATE_RESUME';
export const DELETE_RESUME = 'DELETE_RESUME';

// resume actions constants
export const RESUME_LANGUAGES_LOADING = 'RESUME_LANGUAGES_LOADING';
export const RESUME_LANGUAGES_LOADED = 'RESUME_LANGUAGES_LOADED';
export const RESUME_LANGUAGES_FAILED = 'RESUME_LANGUAGES_FAILED';
export const MAIN_RESUME_LANGUAGES_LOADING = 'MAIN_RESUME_LANGUAGES_LOADING';
export const MAIN_RESUME_LANGUAGES_LOADED = 'MAIN_RESUME_LANGUAGES_LOADED';
export const MAIN_RESUME_LANGUAGES_FAILED = 'MAIN_RESUME_LANGUAGES_FAILED';
export const UPDATE_RESUME_DEFAULT_LANGUAGE = 'UPDATE_RESUME_DEFAULT_LANGUAGE';

// nav intersection observer actions constants
export const UPDATE_NAV_INTERSECTION = 'UPDATE_NAV_INTERSECTION';

// dark theme actions constants
export const SET_THEME_MODE = 'SET_THEME_MODE';

// webp actions constants
export const SET_WEBP_SUPPORT = 'SET_WEBP_SUPPORT';

// username actions constants
export const SET_USERNAME = 'SET_USERNAME';
export const RESET_USERNAME = 'RESET_USERNAME';
